# Generated by Django 4.0 on 2023-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=200, null=True)),
                ('dateUpdate', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('extension', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('callerID', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveChannels5040',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=200, null=True)),
                ('dateUpdate', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('extension', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('callerID', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveChannelsFellows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=200, null=True)),
                ('dateUpdate', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('extension', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('callerID', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Callers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('wait', models.CharField(max_length=10)),
                ('dateUpdate', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Callers5040',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('wait', models.CharField(max_length=10)),
                ('dateUpdate', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CallersFellows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('wait', models.CharField(max_length=10)),
                ('dateUpdate', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.CharField(blank=True, max_length=20, null=True)),
                ('mobileForward', models.CharField(blank=True, max_length=25, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('flag', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('actions', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('Time', models.CharField(default='', max_length=150)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Member5040',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('Time', models.CharField(default='', max_length=150)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MemberFellows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('Time', models.CharField(default='', max_length=150)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Peers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('dateUpdate', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peers5040',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('dateUpdate', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeersFellows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('dateUpdate', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
