# Generated by Django 4.0 on 2023-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='idInternal',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
