# Generated by Django 4.0 on 2023-10-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0002_forward_idinternal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forward',
            name='internal',
        ),
    ]
