# Generated by Django 4.0 on 2023-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0003_remove_forward_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activechannels',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activechannels5040',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activechannelsfellows',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
