# Generated by Django 4.0 on 2024-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(default='', max_length=50)),
                ('time', models.DateTimeField()),
                ('callid', models.CharField(default='', max_length=40)),
                ('queuename', models.CharField(blank=True, max_length=20, null=True)),
                ('serverid', models.CharField(blank=True, max_length=20, null=True)),
                ('agent', models.CharField(blank=True, max_length=40, null=True)),
                ('event', models.CharField(blank=True, max_length=20, null=True)),
                ('data1', models.CharField(blank=True, max_length=40, null=True)),
                ('data2', models.CharField(blank=True, max_length=40, null=True)),
                ('data3', models.CharField(blank=True, max_length=40, null=True)),
                ('data4', models.CharField(blank=True, max_length=40, null=True)),
                ('data5', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
