# Generated by Django 4.0 on 2024-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuelog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
