# Generated by Django 4.0 on 2024-01-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_internal_usershamkadeh_operator_number_and_more'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logonlinehamkadeh',
            name='user',
        ),
        migrations.AddField(
            model_name='logonlinehamkadeh',
            name='consultant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_id', to='User.usershamkadeh'),
        ),
        migrations.AddField(
            model_name='logonlinehamkadeh',
            name='idd',
            field=models.CharField(default='', max_length=43),
        ),
        migrations.AddField(
            model_name='logonlinehamkadeh',
            name='support_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_id', to='User.usershamkadeh'),
        ),
        migrations.CreateModel(
            name='VoipLogOnlineHamkadeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usershamkadeh')),
            ],
        ),
    ]
