# Generated by Django 4.0 on 2024-01-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_internal_usershamkadeh_operator_number_and_more'),
        ('record', '0003_alter_voiplogonlinehamkadeh_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationsHamkadeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('consultant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.usershamkadeh')),
            ],
        ),
    ]
