# Generated by Django 4.1 on 2023-08-26 07:02

import User.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=50, verbose_name='سن')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('phoneNumber2', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن2')),
                ('NameFather', models.CharField(blank=True, max_length=11, null=True, verbose_name=' اسم پدر')),
                ('codeMeli', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=User.models.upload_image_path)),
                ('Age', models.CharField(blank=True, max_length=50, null=True, verbose_name='سن')),
                ('Address', models.TextField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('City', models.CharField(blank=True, max_length=6, null=True)),
                ('HowSee', models.CharField(blank=True, max_length=50, null=True)),
                ('HowSeePerson', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.CharField(blank=True, max_length=100, null=True)),
                ('ActiveUser', models.CharField(blank=True, max_length=150, null=True, verbose_name='فعال بودن کاربر ')),
                ('JobPosition', models.CharField(blank=True, max_length=350, null=True)),
                ('Presenter', models.BooleanField(default=False, verbose_name='مجری ')),
                ('Number', models.IntegerField(blank=True, default=0, null=True)),
                ('Manager', models.BooleanField(default=False)),
                ('BlogManager', models.BooleanField(default=False)),
                ('ProductManager', models.BooleanField(default=False)),
                ('OrderingManager', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
