# Generated by Django 4.0 on 2023-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_internal_user_islistening5040_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isForward',
            field=models.BooleanField(default=False),
        ),
    ]
