# Generated by Django 4.0 on 2023-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_isaddtolinesalehamkadeh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isForward5040',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isForwardHamkadeh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isForwardSaleHamkadeh',
            field=models.BooleanField(default=False),
        ),
    ]
