# Generated by Django 4.0 on 2024-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_users5040_usershamkadeh_user_robot5040_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users5040',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='users5040',
            name='image',
        ),
        migrations.AddField(
            model_name='users5040',
            name='consultant_idd',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='users5040',
            name='profile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='users5040',
            name='support_idd',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
