# Generated by Django 4.0 on 2024-01-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_users5040_idd_remove_users5040_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users5040',
            old_name='internal',
            new_name='operator_number',
        ),
    ]
