# Generated by Django 4.0 on 2024-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_rename_internal_users5040_operator_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershamkadeh',
            old_name='internal',
            new_name='operator_number',
        ),
        migrations.RemoveField(
            model_name='usershamkadeh',
            name='idd',
        ),
        migrations.RemoveField(
            model_name='usershamkadeh',
            name='image',
        ),
        migrations.AddField(
            model_name='usershamkadeh',
            name='consultant_idd',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
        migrations.AddField(
            model_name='usershamkadeh',
            name='profile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usershamkadeh',
            name='support_idd',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
