# Generated by Django 4.0 on 2024-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_internal_usershamkadeh_operator_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='StatusUserHamkadeh',
            field=models.BooleanField(default=False),
        ),
    ]
