# Generated by Django 4.0 on 2024-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_users5040_status_usershamkadeh_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='statusUserHamkadeh',
            new_name='statusConsultantHamkadeh',
        ),
        migrations.AddField(
            model_name='user',
            name='statusSupportHamkadeh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='statusUser5040',
            field=models.BooleanField(default=False),
        ),
    ]
