# Generated by Django 4.0 on 2024-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_rename_statususerhamkadeh_user_statusconsultanthamkadeh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='robotVoip',
            field=models.BooleanField(default=False),
        ),
    ]
